//
//  main.cpp
//  JSONParser
//
//  Created by Aditya Vikram on 13/03/21.
//

#include "lexer.hpp"
#include "parser.hpp"
#include "AllTestCases.hpp"
#include <iostream>
#include "JsonValue.h"

void testJsonValue() {
    using JsonValue = JSONParser::JSONValue;
    JsonValue a;
    assert(a.isNull());
    JsonValue b (1.0);
    assert(b.isDouble());
    assert(b.getDouble() == 1.0);
    assert(b.getOptDouble() == 1.0);
    uint64_t two = 2;
    JsonValue c (two);
    assert(c.isInteger());
    assert(c.getInteger() == two);
    assert(c.getOptInteger() == two);
    JsonValue d ("abc");
    assert(d.isString());
    assert(d.getString() == "abc");
    assert(d.getOptString() == "abc");
    JsonValue e (true);
    assert(e.isBool());
    assert(e.getBool());
    assert(e.getOptBool());
    b = d;
    assert(b.isString());
    assert(b.getString() == "abc");
    assert(b.getOptString() == "abc");
    JsonValue f = c;
    assert(f.isInteger());
    assert(f.getInteger() == two);
    assert(f.getOptInteger() == two);
}

int main() {
//    testJsonValue();
    
//    auto timeElapsed = LexerTestClass::timeLexer(100000, 10);
//    std::cout<< "Time elapsed: " << timeElapsed << " ns\n";
    std::cout << JSONParser::Parser::parse("{\r\n    \"name\": \"John\",\r\n    \"age\": 30,\r\n    \"car\": null,\r\n    \"arr\": [\"abc\",  30]\r\n}\r\n");
    std::cout << JSONParser::Parser::parse("{\r\n    \"_id\": \"604e253c88e106cadf9e015d\",\r\n    \"index\": 0,\r\n    \"guid\": \"783baa61-37a3-41f2-a9b8-8551e35a434d\",\r\n    \"isActive\": false,\r\n    \"balance\": \"$3,487.22\",\r\n    \"picture\": \"http://placehold.it//32x32\",\r\n    \"age\": 40,\r\n    \"eyeColor\": \"green\",\r\n    \"name\": \"Felicia Kirk\",\r\n    \"gender\": \"female\",\r\n    \"company\": \"GRACKER\",\r\n    \"email\": \"feliciakirk@gracker.com\",\r\n    \"phone\": \"+1 (954) 410-3972\",\r\n    \"address\": \"751 Logan Street, Vowinckel, Oklahoma, 4447\",\r\n    \"about\": \"Est ullamco eiusmod proident Lorem ut. Anim occaecat aute sit in velit laborum aliquip sit velit. Labore eiusmod incididunt reprehenderit commodo culpa pariatur nisi. Veniam duis laboris velit do pariatur ut proident commodo commodo. Deserunt incididunt incididunt enim culpa enim culpa sint ex nostrud. Id aliquip consequat eiusmod ullamco dolor aute consectetur culpa deserunt reprehenderit dolore ad cupidatat. Deserunt magna esse excepteur Lorem reprehenderit sint reprehenderit consectetur laboris velit eu fugiat irure.\\r\\n\",\r\n    \"registered\": \"2019-12-15T08:21:23 -06:-30\",\r\n    \"latitude\": 26.21621,\r\n    \"longitude\": 25.728831,\r\n    \"tags\": [\r\n      \"nisi\",\r\n      \"qui\",\r\n      \"esse\",\r\n      \"qui\",\r\n      \"amet\",\r\n      \"ea\",\r\n      \"nostrud\"\r\n    ],\r\n    \"friends\": [\r\n      {\r\n        \"id\": 0,\r\n        \"name\": \"Marissa Wells\"\r\n      },\r\n      {\r\n        \"id\": 1,\r\n        \"name\": \"Coleen Parks\"\r\n      },\r\n      {\r\n        \"id\": 2,\r\n        \"name\": \"Deborah Callahan\"\r\n      }\r\n    ],\r\n    \"greeting\": \"Hello, Felicia Kirk! You have 7 unread messages.\",\r\n    \"favoriteFruit\": \"banana\"\r\n  }");
    std::cout << JSONParser::Parser::parse("{\r\n    \"_id\": \"604e253c4181b16cfffa136e\",\r\n    \"index\": 1,\r\n    \"guid\": \"ecaff1b4-faa2-4f4a-b5a2-e65245a1e96e\",\r\n    \"isActive\": false,\r\n    \"balance\": \"$3,770.43\",\r\n    \"picture\": \"http:/placehold.it/32x32\",\r\n    \"age\": 39,\r\n    \"eyeColor\": \"green\",\r\n    \"name\": \"Barry William\",\r\n    \"gender\": \"male\",\r\n    \"company\": \"EARWAX\",\r\n    \"email\": \"barrywilliam@earwax.com\",\r\n    \"phone\": \"+1 (858) 482-2850\",\r\n    \"address\": \"107 Eastern Parkway, Eastmont, Virgin Islands, 660\",\r\n    \"about\": \"Officia id duis commodo duis id ullamco ex aliqua excepteur nulla excepteur id laborum. Amet pariatur id dolore nostrud minim occaecat dolore cillum dolore est occaecat ipsum. Sunt laboris aliquip laboris enim magna est consequat. Anim excepteur et ex adipisicing duis consectetur nostrud in non irure non Lorem. Deserunt cupidatat non cillum nulla. Lorem laborum magna velit velit aute amet quis dolore sint cillum.\\r\\n\",\r\n    \"registered\": \"2016-12-11T05:12:24 -06:-30\",\r\n    \"latitude\": 25.076848,\r\n    \"longitude\": -155.932439,\r\n    \"tags\": [\r\n      \"sint\",\r\n      \"duis\",\r\n      \"non\",\r\n      \"magna\",\r\n      \"ex\",\r\n      \"quis\",\r\n      \"officia\"\r\n    ],\r\n    \"friends\": [\r\n      {\r\n        \"id\": 0,\r\n        \"name\": \"Larson Mack\"\r\n      },\r\n      {\r\n        \"id\": 1,\r\n        \"name\": \"Cantrell Hanson\"\r\n      },\r\n      {\r\n        \"id\": 2,\r\n        \"name\": \"Silva Reilly\"\r\n      }\r\n    ],\r\n    \"greeting\": \"Hello, Barry William! You have 8 unread messages.\",\r\n    \"favoriteFruit\": \"apple\"\r\n  }");
    std::cout << JSONParser::Parser::parse("{\r\n    \"_id\": \"604e253ccb59448271797387\",\r\n    \"index\": 2,\r\n    \"guid\": \"488ad2b7-58ad-4d0f-b265-ba4193cdacd9\",\r\n    \"isActive\": true,\r\n    \"balance\": \"$1,097.22\",\r\n    \"picture\": \"http://placehold.it/32x32\",\r\n    \"age\": 21,\r\n    \"eyeColor\": \"brown\",\r\n    \"name\": \"Miriam Morse\",\r\n    \"gender\": \"female\",\r\n    \"company\": \"ONTALITY\",\r\n    \"email\": \"miriammorse@ontality.com\",\r\n    \"phone\": \"+1 (948) 593-2260\",\r\n    \"address\": \"106 Butler Place, Gracey, Alaska, 6294\",\r\n    \"about\": \"Ea in culpa ipsum ut amet Lorem incididunt nostrud enim velit aute ut deserunt. Velit aute officia eu do exercitation dolore incididunt consequat occaecat ut cupidatat cillum qui. Incididunt qui labore amet sit. Lorem officia exercitation proident aliquip mollit officia consectetur excepteur quis aliquip. Adipisicing excepteur cillum commodo elit laboris. Reprehenderit ut proident adipisicing tempor cupidatat reprehenderit ipsum tempor excepteur qui elit.\\r\\n\",\r\n    \"registered\": \"2021-02-15T09:08:18 -06:-30\",\r\n    \"latitude\": 59.233292,\r\n    \"longitude\": -87.750318,\r\n    \"tags\": [\r\n      \"qui\",\r\n      \"nisi\",\r\n      \"anim\",\r\n      \"minim\",\r\n      \"ipsum\",\r\n      \"laborum\",\r\n      \"incididunt\"\r\n    ],\r\n    \"friends\": [\r\n      {\r\n        \"id\": 0,\r\n        \"name\": \"Nell Riley\"\r\n      },\r\n      {\r\n        \"id\": 1,\r\n        \"name\": \"Alexandra Turner\"\r\n      },\r\n      {\r\n        \"id\": 2,\r\n        \"name\": \"Curtis Waller\"\r\n      }\r\n    ],\r\n    \"greeting\": \"Hello, Miriam Morse! You have 8 unread messages.\",\r\n    \"favoriteFruit\": \"banana\"\r\n  }");
    std::cout << JSONParser::Parser::parse("{\r\n    \"_id\": \"604e253c52847443ced55f6b\",\r\n    \"index\": 3,\r\n    \"guid\": \"b7900914-f8d5-4e6f-b5a3-bef507ad2d18\",\r\n    \"isActive\": true,\r\n    \"balance\": \"$3,884.72\",\r\n    \"picture\": \"http://placehold.it/32x32\",\r\n    \"age\": 28,\r\n    \"eyeColor\": \"brown\",\r\n    \"name\": \"Anthony Hensley\",\r\n    \"gender\": \"male\",\r\n    \"company\": \"GENMY\",\r\n    \"email\": \"anthonyhensley@genmy.com\",\r\n    \"phone\": \"+1 (917) 502-3387\",\r\n    \"address\": \"740 Commercial Street, Ripley, Massachusetts, 7199\",\r\n    \"about\": \"Fugiat cillum nulla magna dolor amet commodo sit labore voluptate dolor. Cillum ex Lorem irure amet anim minim aliquip nulla adipisicing fugiat. Occaecat qui deserunt adipisicing ullamco sint velit cillum labore minim sit sit consequat fugiat qui.\\r\\n\",\r\n    \"registered\": \"2019-03-26T07:18:33 -06:-30\",\r\n    \"latitude\": -54.920068,\r\n    \"longitude\": 27.327594,\r\n    \"tags\": [\r\n      \"culpa\",\r\n      \"veniam\",\r\n      \"reprehenderit\",\r\n      \"aute\",\r\n      \"reprehenderit\",\r\n      \"consequat\",\r\n      \"Lorem\"\r\n    ],\r\n    \"friends\": [\r\n      {\r\n        \"id\": 0,\r\n        \"name\": \"Gray Flowers\"\r\n      },\r\n      {\r\n        \"id\": 1,\r\n        \"name\": \"Kidd Vinson\"\r\n      },\r\n      {\r\n        \"id\": 2,\r\n        \"name\": \"Thelma Davis\"\r\n      }\r\n    ],\r\n    \"greeting\": \"Hello, Anthony Hensley! You have 2 unread messages.\",\r\n    \"favoriteFruit\": \"strawberry\"\r\n  }");
    std::cout << JSONParser::Parser::parse("{\r\n    \"_id\": \"604e253c1e9d03de58db74b1\",\r\n    \"index\": 4,\r\n    \"guid\": \"33dfc502-d225-4d94-99ab-44e3a8285725\",\r\n    \"isActive\": true,\r\n    \"balance\": \"$1,298.81\",\r\n    \"picture\": \"http://placehold.it/32x32\",\r\n    \"age\": 29,\r\n    \"eyeColor\": \"brown\",\r\n    \"name\": \"Todd Leon\",\r\n    \"gender\": \"male\",\r\n    \"company\": \"ANARCO\",\r\n    \"email\": \"toddleon@anarco.com\",\r\n    \"phone\": \"+1 (830) 535-3073\",\r\n    \"address\": \"401 Lake Place, Nettie, Louisiana, 6302\",\r\n    \"about\": \"Commodo commodo in ipsum ex incididunt. Ipsum laboris ex ipsum nostrud occaecat eiusmod id ad. Eu laboris aliquip ut proident Lorem velit ad.\\r\\n\",\r\n    \"registered\": \"2016-02-01T05:11:00 -06:-30\",\r\n    \"latitude\": 20.79924,\r\n    \"longitude\": 78.199455,\r\n    \"tags\": [\r\n      \"nostrud\",\r\n      \"ea\",\r\n      \"excepteur\",\r\n      \"pariatur\",\r\n      \"duis\",\r\n      \"enim\",\r\n      \"eu\"\r\n    ],\r\n    \"friends\": [\r\n      {\r\n        \"id\": 0,\r\n        \"name\": \"Marcie Norris\"\r\n      },\r\n      {\r\n        \"id\": 1,\r\n        \"name\": \"Rosie Case\"\r\n      },\r\n      {\r\n        \"id\": 2,\r\n        \"name\": \"Stout Combs\"\r\n      }\r\n    ],\r\n    \"greeting\": \"Hello, Todd Leon! You have 10 unread messages.\",\r\n    \"favoriteFruit\": \"apple\"\r\n  }");
    std::cout << JSONParser::Parser::parse("{\r\n    \"_id\": \"604e253c432916db1a72b59e\",\r\n    \"index\": 5,\r\n    \"guid\": \"6b4381a3-1148-46d7-a28f-89a34a4605de\",\r\n    \"isActive\": true,\r\n    \"balance\": \"$2,029.36\",\r\n    \"picture\": \"http://placehold.it/32x32\",\r\n    \"age\": 27,\r\n    \"eyeColor\": \"brown\",\r\n    \"name\": \"Jacquelyn Gallegos\",\r\n    \"gender\": \"female\",\r\n    \"company\": \"ZIDOX\",\r\n    \"email\": \"jacquelyngallegos@zidox.com\",\r\n    \"phone\": \"+1 (977) 404-2743\",\r\n    \"address\": \"744 Prospect Place, Haring, New Mexico, 3277\",\r\n    \"about\": \"Officia sint mollit fugiat minim laborum. Id ipsum est minim fugiat irure fugiat cillum ullamco. Laboris adipisicing consequat ad laboris pariatur cillum veniam.\\r\\n\",\r\n    \"registered\": \"2017-01-29T03:21:13 -06:-30\",\r\n    \"latitude\": 73.008688,\r\n    \"longitude\": 155.828679,\r\n    \"tags\": [\r\n      \"ex\",\r\n      \"cillum\",\r\n      \"consequat\",\r\n      \"officia\",\r\n      \"commodo\",\r\n      \"id\",\r\n      \"fugiat\"\r\n    ],\r\n    \"friends\": [\r\n      {\r\n        \"id\": 0,\r\n        \"name\": \"Gill Weber\"\r\n      },\r\n      {\r\n        \"id\": 1,\r\n        \"name\": \"Lillie Cohen\"\r\n      },\r\n      {\r\n        \"id\": 2,\r\n        \"name\": \"Hill Reeves\"\r\n      }\r\n    ],\r\n    \"greeting\": \"Hello, Jacquelyn Gallegos! You have 10 unread messages.\",\r\n    \"favoriteFruit\": \"apple\"\r\n  }");
    std::cout << JSONParser::Parser::parse("{\r\n    \"_id\": \"604e253cb800e7939e29c1d1\",\r\n    \"index\": 6,\r\n    \"guid\": \"94f94d2f-7205-4924-9f33-1becbeb1cee1\",\r\n    \"isActive\": false,\r\n    \"balance\": \"$3,419.31\",\r\n    \"picture\": \"http://placehold.it/32x32\",\r\n    \"age\": 28,\r\n    \"eyeColor\": \"brown\",\r\n    \"name\": \"Maxwell Allison\",\r\n    \"gender\": \"male\",\r\n    \"company\": \"RONELON\",\r\n    \"email\": \"maxwellallison@ronelon.com\",\r\n    \"phone\": \"+1 (903) 440-3945\",\r\n    \"address\": \"170 Hyman Court, Cresaptown, Nevada, 6159\",\r\n    \"about\": \"Adipisicing laborum irure officia qui magna labore velit est cillum non mollit id tempor velit. Irure Lorem ullamco nulla officia officia non. Lorem proident irure sunt laborum anim sunt ut veniam ipsum aute nulla. Officia aliqua velit deserunt esse cupidatat duis cupidatat non aute. Magna sit adipisicing proident nisi voluptate cillum sunt magna.\\r\\n\",\r\n    \"registered\": \"2015-05-27T07:12:53 -06:-30\",\r\n    \"latitude\": 67.798079,\r\n    \"longitude\": -118.302929,\r\n    \"tags\": [\r\n      \"consequat\",\r\n      \"proident\",\r\n      \"duis\",\r\n      \"nostrud\",\r\n      \"nostrud\",\r\n      \"eiusmod\",\r\n      \"reprehenderit\"\r\n    ],\r\n    \"friends\": [\r\n      {\r\n        \"id\": 0,\r\n        \"name\": \"Pacheco Harrington\"\r\n      },\r\n      {\r\n        \"id\": 1,\r\n        \"name\": \"Mcbride Lancaster\"\r\n      },\r\n      {\r\n        \"id\": 2,\r\n        \"name\": \"Scott Wolfe\"\r\n      }\r\n    ],\r\n    \"greeting\": \"Hello, Maxwell Allison! You have 2 unread messages.\",\r\n    \"favoriteFruit\": \"apple\"\r\n  }");
    return 0;
}
